name: tad_pathways
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::pandas=0.25.1
- conda-forge::numexpr=2.7.0
- conda-forge::numpy=1.17.2
- conda-forge::scipy=1.3.1
- conda-forge::r-base=3.6.1
- conda-forge::r-essentials=3.5.1
- conda-forge::r-codetools=0.2_16
- conda-forge::readline=6.2
- conda-forge::r-readr=1.3.1
- conda-forge::r-gridextra=2.3
- conda-forge::r-optparse=1.6.4
- bioconda::bioconductor-biomart=2.30.0

